image: python:3.6

before_script:
    - pip3 install pycodestyle yapf pylint pytest
    - make install test

stages:
    - check
    - test

variables:
    TEST_FILE: "test/test_database.py"

pylint:
    stage: check
    script:
        - pylint $TEST_FILE

pycodestyle:
    stage: check
    script:
        - pycodestyle $TEST_FILE

yapf:
    stage: check
    script:
        - yapf $TEST_FILE

pytest:
    stage: test
    script:
        - pytest $TEST_FILE

unittest:
    stage: test
    script:
        - make test
