image: python:3.6

before_script:
    - pip3 install pycodestyle yapf pylint pytest
    - make install

stages:
    - check
    - test

variables:
    TEST_FILES_DIR: "test/test_*.py"

pylint:
    stage: check
    script:
        - pylint $TEST_FILES_DIR

pycodestyle:
    stage: check
    script:
        - pycodestyle --max-line-length=99 $TEST_FILES_DIR

yapf:
    stage: check
    script:
        - yapf $TEST_FILES_DIR

pytest:
    stage: test
    script:
        - pytest $TEST_FILES_DIR

unittest:
    stage: test
    script:
        - make test_all
