version: 2.1

executors:
    python35:
        docker:
            - image: circleci/python:3.5.6
        environment:
            - BASH_ENV: /tmp/bashrc
    python36:
        docker:
            - image: circleci/python:3.6.8
        environment:
            - BASH_ENV: /tmp/bashrc
    python37:
        docker:
            - image: circleci/python:3.7.2
        environment:
            - BASH_ENV: /tmp/bashrc

jobs:
    check:
        executor: python37
        steps:
            - checkout
            - run:
                name: Make Composer executables available globally
                command: |
                  echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
                  source $BASH_ENV
            - run:
                name: Install
                command: make setup
            - run:
                name: Lint
                command: make lint
    build:
        executor: python37
        steps:
            - checkout
            - run:
                name: Build geekhours
                command: make build
    test-python35:
        executor: python35
        steps:
            - checkout
            - run:
                name: Make Composer executables available globally
                command: |
                  echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
                  source $BASH_ENV
            - run:
                name: Install geekhours package on python 3.5
                command:
                  make tox
    test-python36:
        executor: python36
        steps:
            - checkout
            - run:
                name: Make Composer executables available globally
                command: |
                  echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
                  source $BASH_ENV
            - run:
                name: Install geekhours package on python 3.6
                command:
                  make tox
    test-python37:
        executor: python37
        steps:
            - checkout
            - run:
                name: Make Composer executables available globally
                command: |
                  echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
                  source $BASH_ENV
            - run:
                name: Install geekhours package on python 3.7
                command: make tox

workflows:
    version: 2.1
    test:
        jobs:
            - check
            - build
            - test-python35
            - test-python36
            - test-python37
